# this workflow will run Pylint on python files (*.py)
# in an active pull request
name: "Pylint"

on:
  workflow_call:
    inputs:
      config-file-path:
        description: "Root relative path to the custom Pylint RC config file (./path/to/rc_file.pylintrc)"
        type: string
        required: false

jobs:
  pylint-files:
    name: "pylint files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "set up Python env"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: "install Pylint"
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: "Run Pylint default configuration"
        if: ${{ inputs.config-file-path == '' }}
        run: |
          git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}} -- '**.py'
          pylint --fail-under=9 $(git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}} -- '**.py')
      - name: "Run Pylint custom configuration"
        if: ${{ inputs.config-file-path != '' }}
        run: |
          git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}} -- '**.py'
          pylint --rcfile=${{inputs.config-file-path}} --fail-under=9 $(git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}} -- '**.py')
